<?php
/**
 * File page.php
 */

 /**
  * Show the UI
  *
  * @return void.
  */
function Call_page()
{
    add_submenu_page(
        'tools.php',
        'Widget I & E', //site title
        'Widget Import & Export', //
        'manage_options', //manage to where to add
        'widgetie', //slug name
        'Widget_page'//callback function
    );
}
add_action('admin_menu', 'Call_page');

/**
 * Show the UI
 *
 * @return Show the UI part.
 */
function Widget_page()
{
    //Gather all the widgets using  $wp_registered_sidebars
    global $wp_registered_sidebars;
    ?>

  <div class="wie-container">
    <form action="tools.php?page=widgetie" method="post" enctype="multipart/form-data">
      <h1>Widget Import Export</h1>
      <h3 class="wie-head">Import Widget Data</h3>

      <div class="notice notice-warning warnning wie-notice wie-notice-warning" id="wie-myDIV">
        <p>Please select a <b>.json</b> file generated by this plugin.
        <a href="http://sarvars.sharkz.in/json/">About JSON File</a></p>
      </div>

      <!-- When user will click on Import button this snippet will be executed  -->
      <?php
        if (isset($_POST['import_button'])) {
            ?>
        <script type="text/javascript">
          show_block();
        </script>

            <?php
            Upload_Import_file();//calling the function in import.php
        }
        ?>     

      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
      <script>
        $(document).ready(function() {
         $('input:file').change(function() {
           if ( $(this).val() ) {
            $('#wie-button-import').removeAttr('disabled');
            }
          }
          );
        });
      </script>

      <!-- The layout of page -->
      <div class="wie-tip">
        <p><i>Please Choose a File To Upload</i></p>
      </div>

      <div class="wie-importsec">
        <input type="file" name="import_filew" id="import-filew"/>
        <input type="hidden" value="true" name="import_button" />
        <button  id="wie-button-import" class="button button-primary" disabled >Import Widget</button>
      </div>
    </form>

    <br><hr class="wie-hr">   

    <h3 class="wie-head">Export Widget Data</h3>

    <?php
    // Exporting the file
    if (isset($_POST['export_button'])) {
        $widget_select=isset($_POST['widget1']);
        if ($widget_select) {
            Download_Export_file();
        } else {
            ?>

        <div class="notice notice-error is-dismissible wie-show-notice" id="myDIV">
          <p>Please select at least one widget to export file.</p>
        </div>
            <?php
        }
    }
    ?>
    <div class="active_widget"><h2>Active Widgets:</h2></div>

    <div class="wie-checkbutton">
      <button class="button button-secondary" onclick="selectAll();">Select All Widget</button>
      <button button id="wie-unselect" class="button button-secondary" onclick="unselectAll();">Unselect All Widget</button>
    </div>

    <form action="tools.php?page=widgetie" method="post" name="form1"enctype="multipart/form-data">
      <?php
        // This calls the generate data function in generatedata.php
        $data11=Generate_Export_data1();

        if ($data11==null) {
            ?>
        <div class="wie-no_widget">No Widget Are Available</div>
            <?php
        }

        // display widgets areas along with their widgets
        foreach ($data11 as $key => $value) {
            ?>
            <?php

            if (isset($wp_registered_sidebars[$key]['name'])) {
                ?>
          <div class="wie-sidebar">
                <?php
                echo $wp_registered_sidebars[$key]['name'];
            } else {
                echo 'inactive_widgets';
            }
            ?>
          </div>
        
          <div class="wie-checkbox" >
            <?php
            foreach ($value as $key1 => $value1) {
                $name=explode("-", $key1)
                ?>
              <input type="checkbox" value="<?php echo ( $key1 ); ?>" name="widget1[]">
                <?php
                echo $name[0].'<br>';
            } ?>
          </div>
            <?php
        }
        ?>
      <div>
        <input type="hidden" value="true" name="export_button"  /><br>
        <button class="button button-primary wie-button-primary" >Export Widget</button>
      </div>
    </form>
  </div>

    <?php
}